CORES = fceumm gambatte gpsp pcsx_rearmed picodrive snes9x2005_plus
CORES+= beetle-pce-fast beetle-vb fake-08 mednafen_supafaust mgba pokemini race

###############################

# optional core vars
# *_REPO=
# *_HASH=
# *_CORE=
# *_FLAGS=
# *_MAKEFILE=
# *_BUILD_PATH=

beetle-pce-fast_REPO = https://github.com/libretro/beetle-pce-fast-libretro
beetle-pce-fast_CORE = mednafen_pce_fast_libretro.so
beetle-pce-fast_HASH = 6210d0f

beetle-vb_REPO = https://github.com/libretro/beetle-vb-libretro
beetle-vb_CORE = mednafen_vb_libretro.so
beetle-vb_HASH = 9d1bd03

fake-08_REPO = https://github.com/jtothebell/fake-08
fake-08_CORE = fake08_libretro.so
fake-08_BUILD_PATH = fake-08/platform/libretro
fake-08_HASH = d98376f

fceumm_REPO = https://github.com/libretro/libretro-fceumm
fceumm_HASH = aebea87

gambatte_REPO = https://github.com/libretro/gambatte-libretro
gambatte_HASH = cbda5ea

mednafen_supafaust_REPO = https://github.com/libretro/supafaust
mednafen_supafaust_HASH = 6b639c9

pcsx_rearmed_MAKEFILE = Makefile.libretro
pcsx_rearmed_HASH = 1fec8a9

picodrive_REPO = https://github.com/irixxxx/picodrive
picodrive_MAKEFILE = Makefile.libretro
picodrive_HASH = c7b771d

pokemini_REPO = https://github.com/libretro/PokeMini
pokemini_MAKEFILE = Makefile.libretro
pokemini_HASH = 9bf4508

snes9x2005_plus_REPO = https://github.com/libretro/snes9x2005
snes9x2005_plus_FLAGS = USE_BLARGG_APU=1
snes9x2005_HASH = fd45b0e

###############################

include ../../all/cores/makefile
